[package]
name = "nu_plugin_llm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nu-plugin = "0.88.1"
nu-protocol = "0.88.1"
openai = { path = "../../crates/services/openai" }
futures = "0.3.30"
