[package]
name = "nu_plugin_hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
nu-plugin = "0.88.1"
nu-protocol = "0.88.1"
